[package]
name = "storm"
version = "0.1.0"
authors = ["Matt Blessed <m@ttblessed.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
env_logger = "0.8.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"
