brace_style                  = "AlwaysNextLine"
control_brace_style          = "AlwaysNextLine"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
# wraps to `comment_width` value
wrap_comments                = true
comment_width                = 80
format_code_in_doc_comments  = true
normalize_comments           = false
